version: '3'

dotenv: ['.env']

tasks:
  all:
    cmds:
      - task: build
      - task: wat
      - task: start
    silent: true

  wat:
    cmds:
      - wasm2wat public/web.wasm > web.wat
    silent: true

  build:
    cmds:
      - c3c compile -O3 --reloc=none --target wasm32 -g0 --link-libc=no --use-stdlib=no --no-entry -o public/web web.c3
      - npm run build
    silent: true
  
  watch:
    cmds:
      - ./node_modules/.bin/tsc -w
    silent: true

  start:
    cmds:
      - npm start
    silent: true
  
  commit:
    cmds:
      - sh -c 'echo "Enter commit description:"; read COMMIT_MSG; echo "$COMMIT_MSG" > .commitmsg; git add .; git commit -F .commitmsg; rm .commitmsg'
    interactive: true
    silent: false
